export const KitxButtonAttributes = {
  "container-background-color": "n/a",
  "css-class": "n/a",
  // button css
  align: "center",
  "background-color": "#414141",
  border: "none",
  "border-bottom": "n/a",
  "border-left": "n/a",
  "border-radius": "3px",
  "border-right": "n/a",
  "border-top": "n/a",
  color: "#ffffff",
  "font-family": "Ubuntu, Helvetica, Arial, sans-serif",
  "font-size": "13px",
  "font-style": "n/a",
  "font-weight": "normal",
  height: "n/a",
  href: "n/a",
  "inner-padding": "10px 25px",
  "letter-spacing": "n/a",
  "line-height": "120%",
  padding: "10px 25px",
  "padding-bottom": "n/a",
  "padding-left": "n/a",
  "padding-right": "n/a",
  "padding-top": "n/a",
  rel: "n/a",
  target: "_blank",
  "text-align": "none",
  "text-decoration": "none",
  "text-transform": "none",
  title: "n/a",
  "vertical-align": "middle",
  width: "n/a",
};
